import React, { useState } from 'react';
import Head from 'next/head'
import Sidebar from '@/components/Sidebar/sidebar';


export default function Home() {
  const [ showSideBar, setShowSideBar ] = useState(true);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='h-screen w-screen bg-[#0A1F1C]'>
        {
          showSideBar &&
          <Sidebar />
        }
      </main>
    </>
  )
}
